Wallet App/src/Web/PaymentSystem.WalletApp.Web/Controllers/TransactionsController.cs
namespace PaymentSystem.WalletApp.Web.Controllers
{
    using System.Threading.Tasks;

    using AutoMapper;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    using Newtonsoft.Json;

    using PaymentSystem.WalletApp.Data.Models;
    using PaymentSystem.WalletApp.Services.Data;
    using PaymentSystem.WalletApp.Web.Infrastructure.Filters.ActionFilters;
    using PaymentSystem.WalletApp.Web.ViewModels.Profile.Accounts;
    using PaymentSystem.WalletApp.Web.ViewModels.Transactions;
    using PaymentSystem.WalletApp.Web.ViewModels.Transactions.SendCoins;
    using PaymentSystem.WalletApp.Web.ViewModels.Transactions.SendCoinsConfirm;

    using static Infrastructure.WebConstants.SendCoinErrorMessages;

    [Authorize]
    public class TransactionsController : BaseController
    {
        private const string SendCoinTempData = "Send Coin Temp Data";

        private readonly IAccountService accountService;
        private readonly IAccountsKeyService accountsKeyService;
        private readonly IMapper mapper;
        private readonly ITransactionService transactionService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IUserService userService;

        public TransactionsController(
            IAccountService accountService,
            IAccountsKeyService accountsKeyService,
            IMapper mapper,
            ITransactionService transactionService,
            UserManager<ApplicationUser> userManager,
            IUserService userService)
        {
            this.accountService = accountService;
            this.accountsKeyService = accountsKeyService;
            this.mapper = mapper;
            this.transactionService = transactionService;
            this.userManager = userManager;
            this.userService = userService;
        }

        public async Task<IActionResult> GetTransactionDetails(string id)
        {
            var activity = await this.transactionService
                .GetTransaction<TransactionDetails>(id);

            return this.Ok(activity);
        }

        [ImportModelState]
        public async Task<IActionResult> SendCoins()
        {
            var userId = this.userManager.GetUserId(this.User);

            var model = new SendCoinsViewModel()
            {
                Accounts = await this.accountService.GetUserAccounts<CoinAccountModel>(userId),
            };

            return this.View(model);
        }

        [HttpPost]
        [ExportModelState]
        public async Task<IActionResult> SendCoins(SendCoinInputModel model)
        {
            var userId = this.userManager.GetUserId(this.User);

            if (!await this.accountService.UserOwnsAccount(model.CoinAccount, userId))
            {
                this.ModelState.AddModelError(string.Empty, CoinAccountErrorMessage);
            }
            else if (!await this.accountService.HasSufficientFunds(model.CoinAccount, model.Amount))
            {
                this.ModelState.AddModelError(string.Empty, InsufficientFundsErrorMessage);
            }

            if (!this.ModelState.IsValid)
            {
                return this.RedirectToAction(nameof(this.SendCoins));
            }

            this.TempData[SendCoinTempData] = JsonConvert.SerializeObject(model);

            return this.RedirectToAction(nameof(this.SendCoinsConfirm));
        }

        public IActionResult SendCoinsConfirm()
        {
            if (!this.TempData.ContainsKey(SendCoinTempData))
            {
                return this.RedirectToAction<TransactionsController>(nameof(this.SendCoins));
            }

            var serializedObject = (string)this.TempData[SendCoinTempData];
            var sendCoinInputModel = JsonConvert.DeserializeObject<SendCoinInputModel>(serializedObject);
            var viewModel = this.mapper.Map<SendCoinsConfirmViewModel>(sendCoinInputModel);

            return this.View(viewModel);
        }

        [HttpPost]
        [ExportModelState]
        public async Task<IActionResult> SendCoinsConfirm(SendCoinConfirmInputModel model)
        {
            var userId = this.userManager.GetUserId(this.User);

            if (!await this.accountService.UserOwnsAccount(model.CoinAccount, userId))
            {
                this.ModelState.AddModelError(string.Empty, CoinAccountErrorMessage);
            }
            else if (!await this.accountService.HasSufficientFunds(model.CoinAccount, model.Amount))
            {
                this.ModelState.AddModelError(string.Empty, InsufficientFundsErrorMessage);
            }

            if (string.IsNullOrWhiteSpace(model.Secret))
            {
                if (!(await this.accountsKeyService.KeyExists(model.CoinAccount)))
                {
                    this.ModelState.AddModelError(string.Empty, MissingAccountKey);
                }
            }

            var success = await this.userService.SendCoins(model.CoinAccount, model.Recipient, model.Amount, model.Secret, userId);

            if (!success)
            {
                this.ModelState.AddModelError(string.Empty, UnSuccessfulOperation);
            }

            if (!this.ModelState.IsValid)
            {
                return this.RedirectToAction(nameof(this.SendCoins));
            }

            return this.RedirectToAction(nameof(this.SendCoinsSuccess));
        }

        public IActionResult SendCoinsSuccess() => this.View();
    }
}

Wallet App/src/Web/PaymentSystem.WalletApp.Web/Controllers/UsersController.cs
namespace PaymentSystem.WalletApp.Web.Controllers
{
    using System;
    using System.Globalization;
    using System.Threading.Tasks;

    using AutoMapper;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    using PaymentSystem.WalletApp.Common;
    using PaymentSystem.WalletApp.Data.Models;
    using PaymentSystem.WalletApp.Services;
    using PaymentSystem.WalletApp.Services.Data;
    using PaymentSystem.WalletApp.Web.Infrastructure.Helpers;
    using PaymentSystem.WalletApp.Web.ViewModels.Users.Dashboard;
    using PaymentSystem.WalletApp.Web.ViewModels.Users.Profile;

    [Authorize]
    public class UsersController : ProfileController
    {
        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly ITransactionService transactionService;

        public UsersController(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            IMapper mapper,
            ICloudinaryService cloudinaryService,
            IUserService userService,
            ITransactionService transactionService) 
            : base(userManager, mapper, cloudinaryService, userService)
        {
            this.signInManager = signInManager;
            this.transactionService = transactionService;
        }

        public async Task<IActionResult> Dashboard()
        {
            var userId = this.userManager.GetUserId(this.User);
            var dashboardUser = await this.userService.GetUser<DashboardUser>(userId);

            dashboardUser.ProfilePictureAddress =
                this.cloudinaryService.GetProfileImageAddress(dashboardUser.ProfilePicture);

            return this.View(dashboardUser);
        }

        public async Task<IActionResult> Profile()
        {
            var profileUser = await this.GetProfileUser();

            return this.View(profileUser);
        }

        [HttpPost]
        public async Task<IActionResult> Profile(PersonalDetailsUpdateModel model)
        {
            if (!this.ModelState.IsValid)
            {
                var profileUser = await this.GetProfileUser();
                return this.View(profileUser);
            }

            var user = await this.userManager.GetUserAsync(this.User);

            user.FirstName = model.FirstName;
            user.LastName = model.LastName;
            user.DateOfBirth = DateTime.ParseExact(model.BirthDate, WalletConstants.BirthDateFormat, CultureInfo.InvariantCulture);

            var address = new Address()
            {
                Street = model.Street,
                City = model.City,
                StateProvince = model.StateProvince,
                Zip = model.ZipCode,
                Country = model.Country
            };

            user.Address = address;

            await this.userManager.UpdateAsync(user);

            var controller = ControllerHelpers.GetControllerName<UsersController>();
            return this.Redirect($"/{controller}/{nameof(this.Profile)}");
        }

        [HttpPost]
        public async Task<IActionResult> EmailUpdate(EmailUpdateModel model)
        {
            if (!this.ModelState.IsValid)
            {
                var profileUser = await this.GetProfileUser();
                return this.View(nameof(this.Profile), profileUser);
            }

            var user = await this.userManager.GetUserAsync(this.User);
            user.Email = model.Email;
            await this.userManager.UpdateAsync(user);

            var controller = ControllerHelpers.GetControllerName<UsersController>();
            return this.Redirect($"/{controller}/{nameof(this.Profile)}");
        }

        [HttpPost]
        public async Task<IActionResult> PhoneUpdate(PhoneUpdateModel model)
        {
            var controller = ControllerHelpers.GetControllerName<UsersController>();

            if (!this.ModelState.IsValid)
            {
                var profileUser = await this.GetProfileUser();
                return this.View(nameof(this.Profile), profileUser);
            }

            var user = await this.userManager.GetUserAsync(this.User);
            user.PhoneNumber = model.Phone;
            await this.userManager.UpdateAsync(user);

            return this.Redirect($"/{controller}/{nameof(this.Profile)}");
        }

        [HttpPost]
        public async Task<IActionResult> UploadPicture([FromForm] IFormFile profilePicture)
        {
            var controller = ControllerHelpers.GetControllerName<UsersController>();

            if (!this.ModelState.IsValid)
            {
                var profileUser = await this.GetProfileUser();
                return this.View(nameof(this.Profile), profileUser);
            }

            var profilePictureAddress = await this.cloudinaryService.Upload(profilePicture);

            var user = await this.userManager.GetUserAsync(this.User);
            user.ProfilePicture = profilePictureAddress;
            await this.userManager.UpdateAsync(user);

            return this.Redirect($"/{controller}/{nameof(this.Profile)}");
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordModel model)
        {
            var controller = ControllerHelpers.GetControllerName<UsersController>();

            if (!this.ModelState.IsValid)
            {
                var profileUser = await this.GetProfileUser();
                return this.View(nameof(this.Profile), profileUser);
            }

            var user = await this.userManager.GetUserAsync(this.User);

            var result = await this.signInManager.UserManager
                .ChangePasswordAsync(user, model.Password, model.NewPassword);

            if (!result.Succeeded)
            {
                foreach (var error in result.Errors)
                {
                    this.ModelState.AddModelError(string.Empty, error.Description);
                }

                var profileUser = await this.GetProfileUser();
                return this.View(nameof(this.Profile), profileUser);
            }

            return this.Redirect($"/{controller}/{nameof(this.Profile)}");
        }

        private async Task<ProfileUserViewModel> GetProfileUser()
        {
            var profileUser = await this.GetProfileUser<ProfileUserViewModel>();

            profileUser.Address ??= new Address();

            return profileUser;
        }
    }
}

Wallet App/src/Web/PaymentSystem.WalletApp.Web/Views/Transactions/SendCoins.cshtml
@using PaymentSystem.WalletApp.Common
@model PaymentSystem.WalletApp.Web.ViewModels.Transactions.SendCoins.SendCoinsViewModel

@{
    Layout = "/Views/Shared/_Layout.cshtml";
}

@section Scripts
{
    <script>
        const accountSecrets = {};

        @foreach (var d in Model.Accounts)
        {
            @:accountSecrets["@d.Address"] = @d.HasStoredKey.ToString().ToLower();
        }

        setAccountSecret();

        function setAccountSecret() {
            const coinAccount = document.getElementById('withdraw-from');
            const accountSecret = document.getElementById('account-secret');

            if (accountSecrets[coinAccount.value]) {
                accountSecret.value = true;
            } else {
                accountSecret.value = false;
            }
        };

        function coinAccountChangeHandler() {
            setAccountSecret();
        };

        function onAmountChangeHandler(el) {
            const value = parseFloat(el.value);

            const feesPercent = @(WalletConstants.DefaultFeePercent / 100);
            const fees = value * feesPercent;
            const total = value + fees;

            const sendFees = document.getElementById('send-fees');
            sendFees.textContent = `${fees.toFixed(2)} P`;

            const sendTotal = document.getElementById('send-total');
            sendTotal.textContent = `${total.toFixed(2)} P`;
        }
    </script>
}

<!-- Content ============================================= -->
<div id="content" class="py-4">
    <div class="container">
        <div class="col-12 text-danger" asp-validation-summary="All"></div>
        <h2 class="font-weight-400 text-center mt-3">Send Money</h2>
        <p class="text-4 text-center mb-4">Send your money on anytime, anywhere in the world.</p>
        <div class="row">
            <div class="col-md-8 col-lg-6 col-xl-5 mx-auto">
                <div class="bg-light shadow-sm rounded p-3 p-sm-4 mb-4">
                    <div class="card mb-4 shadow bg-white rounded">
                        <div class="card-body text-warning text-center">
                            Warning sending coins to invalid address will result in coin loss.
                        </div>
                    </div>
                    <h3 class="text-5 font-weight-400 mb-3">Transaction Details</h3>
                    <!-- Send Money Form ============================================= -->
                    <form id="form-send-money" method="post">
                        <div class="form-group">
                            <label for="withdraw-from">Coin Account</label>
                            <select name="coinAccount" onchange="coinAccountChangeHandler()" id="withdraw-from" asp-items="@this.Model.Coins" class="custom-select" required="required">
                            </select>
                        </div>
                        <input type="hidden" name="hasKey" id="account-secret">
                        <div class="form-group">
                            <label for="emailID">Recipient Address</label>
                            <input name="Recipient" type="text" value="" class="form-control" data-bv-field="emailid" id="emailID" required placeholder="Enter Recipient Address">
                        </div>
                        <div class="form-group">
                            <label for="transaction-amount">Amount</label>
                            <div class="input-group">
                                <div class="input-group-prepend"> <span class="input-group-text">P</span> </div>
                                <input name="amount" type="number" oninput="onAmountChangeHandler(this)" class="form-control" data-bv-field="youSend" id="transaction-amount" step="any" placeholder="1000.00">
                            </div>
                        </div>
                        <hr>
                        <p class="text-muted mt-4">Total fees <span id="send-fees" class="text-3 float-right">0.00 P</span></p>
                        <p class="font-weight-500">Total To Pay <span id="send-total" class="text-3 float-right">0.00 P</span></p>
                        <button class="btn btn-primary btn-block">Continue</button>
                    </form>
                    <!-- Send Money Form end -->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Content end --> 

Wallet App/src/Web/PaymentSystem.WalletApp.Web/Views/Transactions/SendCoinsConfirm.cshtml
@model PaymentSystem.WalletApp.Web.ViewModels.Transactions.SendCoinsConfirm.SendCoinsConfirmViewModel

@{
    Layout = "/Views/Shared/_Layout.cshtml";
}


<!-- Content ============================================= -->
<div id="content" class="py-4">
    <div class="container">
        <h2 class="font-weight-400 text-center mt-3">Send Money</h2>
        <p class="text-4 text-center mb-4">Send your money on anytime, anywhere in the world.</p>
        <div class="row">
            <div class="col-lg-10 col-xl-8 mx-auto">
                <div class="bg-light shadow-sm rounded p-3 p-sm-4 mb-4">
                    <div class="card mb-4 shadow bg-white rounded">
                        <div class="card-body text-warning text-center">
                            Warning sending coins to invalid address will result in coin loss.
                        </div>
                    </div>
                    <h3 class="text-5 font-weight-400 mb-3">Transaction Details</h3>
                    <!-- Send Money Form ============================================= -->
                    <form id="form-send-money" method="post">
                        <div class="form-group">
                            <label for="withdraw-from">Coin Account Address</label>
                            <input name="coinAccount" value="@Model.CoinAccount" readonly="readonly" type="text" id="withdraw-from" class="form-control" />
                        </div>
                        @if (!this.Model.HasKey)
                        {
                            <div id="account-secret-group" class="form-group">
                                <div class="form-group">
                                    <label for="account-secret">Account Secret</label>
                                    <input name="secret" type="text" id="account-secret" class="form-control" />
                                </div>
                            </div>
                        }
                        <div class="form-group">
                            <label for="recipient-address">Recipient Address</label>
                            <input name="Recipient" value="@Model.Recipient" readonly="readonly" type="text" id="recipient-address" class="form-control" required placeholder="Enter Recipient Address">
                        </div>
                        <div class="form-group">
                            <label for="transaction-amount">Amount</label>
                            <div class="input-group">
                                <div class="input-group-prepend"> <span class="input-group-text">P</span> </div>
                                <input name="amount" value="@Model.Amount.ToString("F2")" readonly="readonly" type="number" class="form-control" data-bv-field="youSend" id="transaction-amount" step="any" placeholder="1000.00">
                            </div>
                        </div>
                        <hr>
                        <p class="text-muted mt-4">Total fees <span id="send-fees" class="text-3 float-right">@this.Model.Fees.ToString("F2") P</span></p>
                        <p class="font-weight-500">Total To Pay <span id="send-total" class="text-3 float-right">@this.Model.TotalAmount.ToString("F2") P</span></p>
                        <button class="btn btn-primary btn-block">Send Coins</button>
                    </form>
                    <!-- Send Money Form end -->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Content end --> 

Wallet App/src/Web/PaymentSystem.WalletApp.Web/Views/Transactions/SendCoinsSuccess.cshtml
@{
    Layout = "/Views/Shared/_Layout.cshtml";
}

<!-- Content
============================================= -->
<div id="content" class="py-4">
    <div class="container">
        <h2 class="font-weight-400 text-center mt-3 mb-4">Send Money</h2>
        <div class="row">
            <div class="col-md-8 col-lg-6 col-xl-5 mx-auto">
                <!-- Send Money Success
                ============================================= -->
                <div class="bg-light shadow-sm rounded p-3 p-sm-4 mb-4">
                    <div class="text-center my-5">
                        <p class="text-center text-success text-20 line-height-07"><i class="fas fa-check-circle"></i></p>
                        <p class="text-center text-success text-8 line-height-07">Success!</p>
                        <p class="text-center text-4">Transactions Complete</p>
                    </div>
                    <p class="text-center text-3 mb-4">
                        You've successfully sent
                        <span class="text-4 font-weight-500">pirocoins</span>,
                        See transaction details under
                        <a asp-area="Profile" asp-controller="Users" asp-action="Dashboard">Dashboard</a>.
                    </p>
                    <a asp-area="" asp-controller="Transactions" asp-action="SendCoins" class="btn btn-primary btn-block">Send Money Again</a>
                    <button onclick="window.print()" class="btn btn-link btn-block"><i class="fas fa-print"></i> Print</button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Content end -->

Wallet App/src/Web/PaymentSystem.WalletApp.Web/Views/Transactions/TransactionDetailsModal.cshtml
<!-- Transaction Item Details Modal =========================================== -->
<div id="transaction-detail" class="modal fade" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered transaction-details" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div class="row no-gutters">
                    <div class="col-sm-5 d-flex justify-content-center bg-primary rounded-left py-4">
                        <div class="my-auto text-center">
                            <div class="text-17 text-white my-3"><i class="fas fa-building"></i></div>
                            <h3 class="text-4 text-white font-weight-400 my-3">XXX</h3>
                            <div id="total-amount-header" class="text-8 font-weight-500 text-white my-4">00.00P</div>
                            <p id="date-header" class="text-white"></p>
                        </div>
                    </div>
                    <div class="col-sm-7">
                        <h5 class="text-5 font-weight-400 m-3">
                            Transaction Details
                            <button type="button" class="close font-weight-400" data-dismiss="modal" aria-label="Close"> <span aria-hidden="true">&times;</span> </button>
                        </h5>
                        <hr>
                        <div class="px-3">
                            <ul class="list-unstyled">
                                <li class="mb-2">Payment Amount <span id="payment-amount" class="float-right text-3">00.00P</span></li>
                                <li class="mb-2">Fee <span id="transaction-fee" class="float-right text-3">-0.00P</span></li>
                            </ul>
                            <hr class="mb-2">
                            <p class="d-flex align-items-center font-weight-500 mb-4">
                                Total Amount
                                <span id="total-amount" class="text-3 ml-auto">00.00P</span>
                            </p>
                            <ul class="card list-unstyled coin-account-details-card">
                                <li class="font-weight-500">Sender Address:</li>
                                <li id="sender-address" class="text-muted">XXXX</li>
                            </ul>
                            <ul class="card list-unstyled coin-account-details-card">
                                <li class="font-weight-500">Recipient Address:</li>
                                <li id="recipient-address" class="text-muted">XXXX</li>
                            </ul>
                            <ul class="card list-unstyled coin-account-details-card">
                                <li class="font-weight-500">Transaction Hash:</li>
                                <li id="transaction-hash" class="text-muted">-----</li>
                            </ul>
                            <ul class="card list-unstyled coin-account-details-card">
                                <li class="font-weight-500">Block Hash:</li>
                                <li id="block-hash" class="text-muted">-----</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Transaction Item Details Modal End -->