Wallet App/src/Web/PaymentSystem.WalletApp.Web/Controllers/AccountsController.cs
namespace PaymentSystem.WalletApp.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    using PaymentSystem.WalletApp.Data.Models;
    using PaymentSystem.WalletApp.Services.Data;
    using PaymentSystem.WalletApp.Web.ViewModels.Accounts.Index;
    using PaymentSystem.WalletApp.Web.ViewModels.Accounts.Transactions;

    using static Infrastructure.WebConstants;

    [Authorize]
    public class AccountsController : BaseController
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IAccountService accountService;
        private readonly ITransactionService transactionService;

        public AccountsController(
            UserManager<ApplicationUser> userManager,
            IAccountService accountService,
            ITransactionService transactionService)
        {
            this.userManager = userManager;
            this.accountService = accountService;
            this.transactionService = transactionService;
        }

        public async Task<IActionResult> Index()
        {
            var userId = this.userManager.GetUserId(this.User);

            var model = new AccountsIndexVewModel()
            {
                Accounts = await this.accountService.GetUserAccounts<AccountIndexListingModel>(userId),
            };

            return this.View(model);
        }

        public async Task<IActionResult> Transactions(string address, int page = 1)
        {
            page = Math.Max(page, 1);

            var userId = this.userManager.GetUserId(this.User);

            if (!await this.accountService.UserOwnsAccount(address, userId))
            {
                return this.RedirectToAction(nameof(this.Index));
            }

            var (totalTransactions, transactions) = await this.transactionService
                .GetTransactionsForAddress<AccountsTransactionsListingModel>(address, page, DefaultTransactionsResultPageSize);

            transactions = transactions.ToList();

            foreach (var transaction in transactions)
            {
                transaction.CurrentAccountAddress = address;
            }

            var model = new AccountsTransactionsViewModel()
            {
                Transactions = transactions,
                CurrentAccountAddress = address,
                CurrentPage = page,
                TotalPages = (int)Math.Ceiling(totalTransactions / (double)DefaultTransactionsResultPageSize),
            };

            return this.View(model);
        }
    }
}

Wallet App/src/Web/PaymentSystem.WalletApp.Web/Controllers/TransfersController.cs
namespace PaymentSystem.WalletApp.Web.Controllers
{
    using System.Threading.Tasks;

    using AutoMapper;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    using Newtonsoft.Json;

    using PaymentSystem.Common;
    using PaymentSystem.WalletApp.Data.Models;
    using PaymentSystem.WalletApp.Services.Data;
    using PaymentSystem.WalletApp.Services.Data.Models;
    using PaymentSystem.WalletApp.Services.Data.Models.Transactions;
    using PaymentSystem.WalletApp.Web.Infrastructure;
    using PaymentSystem.WalletApp.Web.Infrastructure.Filters.ActionFilters;
    using PaymentSystem.WalletApp.Web.ViewModels.Transfers.Deposit;
    using PaymentSystem.WalletApp.Web.ViewModels.Transfers.DepositConfirm;
    using PaymentSystem.WalletApp.Web.ViewModels.Transfers.Withdraw;

    using static PaymentSystem.WalletApp.Web.Infrastructure.WebConstants.TransfersErrorMessages;

    [Authorize]
    public class TransfersController : BaseController
    {
        private const string DepositTempData = "depositTempData";

        private readonly UserManager<ApplicationUser> userManager;
        private readonly IMapper mapper;
        private readonly IAccountService accountService;
        private readonly IBankAccountService bankAccountService;
        private readonly ICreditCardService creditCardService;
        private readonly ITransferService transferService;
        private readonly IUserService userService;

        public TransfersController(
            UserManager<ApplicationUser> userManager,
            IMapper mapper,
            IAccountService accountService,
            IBankAccountService bankAccountService,
            ICreditCardService creditCardService,
            ITransferService transferService,
            IUserService userService)
        {
            this.userManager = userManager;
            this.mapper = mapper;
            this.accountService = accountService;
            this.bankAccountService = bankAccountService;
            this.creditCardService = creditCardService;
            this.transferService = transferService;
            this.userService = userService;
        }

        [ImportModelState]
        public IActionResult Deposit()
        {
            return this.View();
        }

        [HttpPost]
        [ExportModelState]
        public IActionResult Deposit(DepositModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.RedirectToAction(nameof(this.Deposit));
            }

            this.TempData[DepositTempData] = JsonConvert.SerializeObject(model);

            return this.RedirectToAction(nameof(this.DepositConfirm));
        }

        public async Task<IActionResult> DepositConfirm()
        {
            if (!this.TempData.ContainsKey(DepositTempData))
            {
                return this.RedirectToAction(nameof(this.Deposit));
            }

            var serializedObject = (string)this.TempData[DepositTempData];
            var depositModel = JsonConvert.DeserializeObject<DepositModel>(serializedObject);
            var userId = this.userManager.GetUserId(this.User);

            var model = new DepositConfirmModel()
            {
                Amount = depositModel.Amount,
                Total = depositModel.Amount,
                PaymentMethod = depositModel.PaymentMethod,
                PaymentMethods = await this.userService.GetPaymentMethods(userId, depositModel.PaymentMethod),
                Accounts = await this.userService.GetCoinAccounts(userId),
            };

            return this.View(model);
        }

        [HttpPost]
        [ExportModelState]
        public async Task<IActionResult> DepositConfirm(DepositConfirmInputModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.RedirectToAction(nameof(this.Deposit));
            }

            var userId = this.userManager.GetUserId(this.User);
            var userOwnsAccount = await this.accountService.UserOwnsAccount(model.Account, userId);
            var isPaymentMethodValid = model.PaymentType switch
            {
                PaymentMethod.BankAccount => await this.bankAccountService.UserOwnsAccount(model.PaymentMethod, userId),
                PaymentMethod.CreditOrDebitCard => await this.creditCardService.UserOwnsCard(model.PaymentMethod, userId),
                _ => false,
            };

            if (!userOwnsAccount || !isPaymentMethodValid)
            {
                this.ModelState.AddModelError(string.Empty, InvalidPaymentMethod);
                return this.RedirectToAction(nameof(this.Deposit));
            }

            var serviceModel = new DepositServiceModel()
            {
                Amount = model.Amount,
                Fee = GlobalConstants.DefaultDepositFee,
                RecipientAddress = model.Account,
            };

            if (!await this.transferService.DepositToAccount(userId, serviceModel))
            {
                this.ModelState.AddModelError(string.Empty, UnSuccessfulDeposit);
                return this.RedirectToAction(nameof(this.Deposit));
            }

            if (model.PaymentType is PaymentMethod.BankAccount)
            {
                await this.bankAccountService.ConfirmAccount(model.PaymentMethod);
            }

            return this.RedirectToAction(nameof(this.DepositSuccess));
        }

        public IActionResult DepositSuccess() => this.View();

        [ImportModelState]
        public async Task<IActionResult> Withdraw()
        {
            var userId = this.userManager.GetUserId(this.User);
            var model = await this.userService.GetUser<WithdrawViewModel>(userId);

            return this.View(model);
        }

        [HttpPost]
        [ExportModelState]
        public async Task<IActionResult> Withdraw(WithdrawInputModel model)
        {
            var userId = this.userManager.GetUserId(this.User);

            if (!await this.bankAccountService.Exists(model.BankAccount)
                || !await this.bankAccountService.UserOwnsAccount(model.BankAccount, userId)
                || !await this.bankAccountService.AccountIsConfirmed(model.BankAccount))
            {
                this.ModelState.AddModelError(string.Empty, WebConstants.WithdrawInputModel.BankAccountErrorMessage);
            }

            if (!await this.accountService.Exists(model.CoinAccount)
                || !await this.accountService.UserOwnsAccount(model.CoinAccount, userId))
            {
                this.ModelState.AddModelError(string.Empty, WebConstants.WithdrawInputModel.CoinAccountErrorMessage);
            }
            else if (!await this.accountService.HasSufficientFunds(model.CoinAccount, model.Amount))
            {
                this.ModelState.AddModelError(string.Empty, WebConstants.WithdrawInputModel.InsufficientFundsErrorMessage);
            }

            if (!this.ModelState.IsValid)
            {
                return this.RedirectToAction(nameof(this.Withdraw));
            }

            var serviceModel = this.mapper.Map<WithdrawServiceModel>(model);

            if (!await this.transferService.WithdrawFromAccount(userId, serviceModel))
            {
                this.ModelState.AddModelError(string.Empty, UnSuccessfulWithdraw);

                this.RedirectToAction(nameof(this.Withdraw));
            }

            return this.RedirectToAction(nameof(this.WithdrawSuccess));
        }

        public IActionResult WithdrawSuccess() => this.View();
    }
}

Wallet App/src/Web/PaymentSystem.WalletApp.Web/Controllers/UsersController.cs
namespace PaymentSystem.WalletApp.Web.Controllers
{
    using System;
    using System.Globalization;
    using System.Threading.Tasks;

    using AutoMapper;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    using PaymentSystem.WalletApp.Common;
    using PaymentSystem.WalletApp.Data.Models;
    using PaymentSystem.WalletApp.Services;
    using PaymentSystem.WalletApp.Services.Data;
    using PaymentSystem.WalletApp.Web.Infrastructure.Helpers;
    using PaymentSystem.WalletApp.Web.ViewModels.Users.Dashboard;
    using PaymentSystem.WalletApp.Web.ViewModels.Users.Profile;

    [Authorize]
    public class UsersController : ProfileController
    {
        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly ITransactionService transactionService;

        public UsersController(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            IMapper mapper,
            ICloudinaryService cloudinaryService,
            IUserService userService,
            ITransactionService transactionService) 
            : base(userManager, mapper, cloudinaryService, userService)
        {
            this.signInManager = signInManager;
            this.transactionService = transactionService;
        }

        public async Task<IActionResult> Dashboard()
        {
            var userId = this.userManager.GetUserId(this.User);
            var dashboardUser = await this.userService.GetUser<DashboardUser>(userId);

            dashboardUser.ProfilePictureAddress =
                this.cloudinaryService.GetProfileImageAddress(dashboardUser.ProfilePicture);

            return this.View(dashboardUser);
        }

        public async Task<IActionResult> Profile()
        {
            var profileUser = await this.GetProfileUser();

            return this.View(profileUser);
        }

        [HttpPost]
        public async Task<IActionResult> Profile(PersonalDetailsUpdateModel model)
        {
            if (!this.ModelState.IsValid)
            {
                var profileUser = await this.GetProfileUser();
                return this.View(profileUser);
            }

            var user = await this.userManager.GetUserAsync(this.User);

            user.FirstName = model.FirstName;
            user.LastName = model.LastName;
            user.DateOfBirth = DateTime.ParseExact(model.BirthDate, WalletConstants.BirthDateFormat, CultureInfo.InvariantCulture);

            var address = new Address()
            {
                Street = model.Street,
                City = model.City,
                StateProvince = model.StateProvince,
                Zip = model.ZipCode,
                Country = model.Country
            };

            user.Address = address;

            await this.userManager.UpdateAsync(user);

            var controller = ControllerHelpers.GetControllerName<UsersController>();
            return this.Redirect($"/{controller}/{nameof(this.Profile)}");
        }

        [HttpPost]
        public async Task<IActionResult> EmailUpdate(EmailUpdateModel model)
        {
            if (!this.ModelState.IsValid)
            {
                var profileUser = await this.GetProfileUser();
                return this.View(nameof(this.Profile), profileUser);
            }

            var user = await this.userManager.GetUserAsync(this.User);
            user.Email = model.Email;
            await this.userManager.UpdateAsync(user);

            var controller = ControllerHelpers.GetControllerName<UsersController>();
            return this.Redirect($"/{controller}/{nameof(this.Profile)}");
        }

        [HttpPost]
        public async Task<IActionResult> PhoneUpdate(PhoneUpdateModel model)
        {
            var controller = ControllerHelpers.GetControllerName<UsersController>();

            if (!this.ModelState.IsValid)
            {
                var profileUser = await this.GetProfileUser();
                return this.View(nameof(this.Profile), profileUser);
            }

            var user = await this.userManager.GetUserAsync(this.User);
            user.PhoneNumber = model.Phone;
            await this.userManager.UpdateAsync(user);

            return this.Redirect($"/{controller}/{nameof(this.Profile)}");
        }

        [HttpPost]
        public async Task<IActionResult> UploadPicture([FromForm] IFormFile profilePicture)
        {
            var controller = ControllerHelpers.GetControllerName<UsersController>();

            if (!this.ModelState.IsValid)
            {
                var profileUser = await this.GetProfileUser();
                return this.View(nameof(this.Profile), profileUser);
            }

            var profilePictureAddress = await this.cloudinaryService.Upload(profilePicture);

            var user = await this.userManager.GetUserAsync(this.User);
            user.ProfilePicture = profilePictureAddress;
            await this.userManager.UpdateAsync(user);

            return this.Redirect($"/{controller}/{nameof(this.Profile)}");
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordModel model)
        {
            var controller = ControllerHelpers.GetControllerName<UsersController>();

            if (!this.ModelState.IsValid)
            {
                var profileUser = await this.GetProfileUser();
                return this.View(nameof(this.Profile), profileUser);
            }

            var user = await this.userManager.GetUserAsync(this.User);

            var result = await this.signInManager.UserManager
                .ChangePasswordAsync(user, model.Password, model.NewPassword);

            if (!result.Succeeded)
            {
                foreach (var error in result.Errors)
                {
                    this.ModelState.AddModelError(string.Empty, error.Description);
                }

                var profileUser = await this.GetProfileUser();
                return this.View(nameof(this.Profile), profileUser);
            }

            return this.Redirect($"/{controller}/{nameof(this.Profile)}");
        }

        private async Task<ProfileUserViewModel> GetProfileUser()
        {
            var profileUser = await this.GetProfileUser<ProfileUserViewModel>();

            profileUser.Address ??= new Address();

            return profileUser;
        }
    }
}

Wallet App/src/Web/PaymentSystem.WalletApp.Web/Views/Shared/_Layout.cshtml
@using PaymentSystem.WalletApp.Common
@using PaymentSystem.WalletApp.Data.Models
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, shrink-to-fit=no">

    <meta name="title" content="Pirocoin crypto currency, money trasfer and online payments">
    <meta name="description" content="Blockchain based monetary system. Make money transfers and online payments.">
    <meta name="author" content="github.com/pirocorp">

    <title>@this.ViewData["Title"]</title>

    <link href="/favicon.ico" rel="shortcut icon" type="image/x-icon">
    <link href="/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Web Fonts ============================================= -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Rubik:300,300i,400,400i,500,500i,700,700i,900,900i"
          type="text/css">

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/custom.css" asp-append-version="true" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet"
              href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only"
              asp-fallback-test-property="position"
              asp-fallback-test-value="absolute"
              integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l"
              crossorigin="anonymous" />

        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
              asp-fallback-href="~/lib/font-awesome/css/all.min.css"
              asp-fallback-test-class="fa-lg"
              asp-fallback-test-property="font-size"
              asp-fallback-test-value="1.33333em"
              integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
              crossorigin="anonymous" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @await this.RenderSectionAsync("Styles", required: false)
</head>

<body>
    <!-- PreLoader -->
    <div id="preloader">
        <div data-loader="dual-ring"></div>
    </div>
    <!-- PreLoader End -->

    <!-- Document Wrapper ============================================= -->
    <div id="main-wrapper">
        
        <!-- Header ============================================= -->
        <header id="header" class="bg-dark-2 header-text-light">
            <div class="container">
                <div class="header-row">
                    <div class="header-column justify-content-start">
                        
                        <!-- Logo ============================= -->
                        <div class="logo">
                            <a class="d-flex" asp-area="" asp-controller="Home" asp-action="Index" title="PIROCOIN">
                                <img class="pirocoin-logo-white" src="/logos/pirocoin-white.png" alt="Pirocoin" />
                            </a>
                        </div>
                        <!-- Logo end -->
                        
                        <!-- Collapse Button ============================== -->
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#header-nav"> <span></span> <span></span> <span></span> </button>
                        <!-- Collapse Button end -->
                        
                        <!-- Primary Navigation ============================== -->
                        <nav class="primary-menu navbar navbar-expand-lg">
                            <div id="header-nav" class="collapse navbar-collapse">
                                <ul class="navbar-nav mr-auto">
                                    @if (this.SignInManager.IsSignedIn(this.User))
                                    {
                                        <li is-active-route="active" asp-area="Profile" asp-controller="Users" asp-action="Dashboard">
                                            <a asp-area="Profile" asp-controller="Users" asp-action="Dashboard">Dashboard</a>
                                        </li>
                                        <li>
                                            <a asp-area="" asp-controller="Transfers" asp-action="Deposit">Deposit / Withdraw</a>
                                        </li>
                                        <li is-active-route="active" asp-area="" asp-controller="Transactions" asp-action="SendCoins">
                                            <a asp-area="" asp-controller="Transactions" asp-action="SendCoins">Send Coins</a>
                                        </li>
                                    }
                                    else
                                    {
                                        <li><a href="about-us.html">About Us</a></li>
                                    }
                                    <li class="dropdown">
                                        <a class="dropdown-toggle dropdown-toggle" href="#">Explorer</a>
                                        <ul class="dropdown-menu">
                                            <li class="dropdown">
                                                <a class="dropdown-item" href="#">Browse Blocks</a>
                                            </li>
                                            <li class="dropdown">
                                                <a class="dropdown-item" href="#">Genesis Block</a>
                                            </li>
                                            <li class="dropdown">
                                                <a class="dropdown-item" href="#">Last Block</a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </nav>
                        <!-- Primary Navigation end -->

                    </div>
                    <div class="header-column justify-content-end">
                        <!-- Login & SignUp Link  ============================== -->
                        <nav class="login-signup navbar navbar-expand">
                            <partial name="_LoginPartial" />
                        </nav>
                        <!-- Login & SignUp Link end -->
                    </div>
                </div>
            </div>
        </header>
        <!-- Header End -->

        @await this.RenderSectionAsync("SecondaryMenu", required: false)

        <partial name="_CookieConsentPartial" />

        <!-- Main Content -->
        <div id="content">
            <main>
                @this.RenderBody()
            </main>
        </div>
        <!-- Main Content -->
        
        <!-- Footer ============================================= -->
        <footer id="footer" class="bg-dark-2 pirocoin-footer-dark footer-text-light border-0">
            <div class="container">
                <div class="row">
                    <div class="col-lg d-lg-flex align-items-center">
                        <span>Powered by</span>
                        &nbsp;
                        <a asp-area="" asp-controller="Home" asp-action="Index"> blockchain</a>.
                    </div>

                    <div class="col-lg d-lg-flex justify-content-lg-end mt-3 mt-lg-0">
                        <ul class="social-icons social-icons-light justify-content-center">
                            <li class="social-icons-facebook"><a data-toggle="tooltip" href="http://www.facebook.com/" target="_blank" title="" data-original-title="Facebook"><i class="fab fa-facebook-f"></i></a></li>
                            <li class="social-icons-twitter"><a data-toggle="tooltip" href="http://www.twitter.com/" target="_blank" title="" data-original-title="Twitter"><i class="fab fa-twitter"></i></a></li>
                            <li class="social-icons-google"><a data-toggle="tooltip" href="http://www.google.com/" target="_blank" title="" data-original-title="Google"><i class="fab fa-google"></i></a></li>
                            <li class="social-icons-youtube"><a data-toggle="tooltip" href="http://www.youtube.com/" target="_blank" title="" data-original-title="Youtube"><i class="fab fa-youtube"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="footer-copyright pt-3 pt-lg-2 mt-2">
                    <div class="row">
                        <div class="col-lg">
                            <p class="text-center text-lg-left mb-2 mb-lg-0">Copyright &copy; 2021 @(DateTime.Now.Year > 2021 ? $"- {DateTime.Now.Year}" : string.Empty) <a asp-area="" asp-controller="Home" asp-action="Index">@WalletConstants.SystemName</a>. All Rights Reserved.</p>
                        </div>
                        <div class="col-lg d-lg-flex align-items-center justify-content-lg-end">
                            <ul class="nav justify-content-center">
                                <li class="nav-item"> <a class="nav-link active" href="#">Security</a></li>
                                <li class="nav-item"> <a class="nav-link" href="#">Terms</a></li>
                                <li class="nav-item"> <a class="nav-link" href="#">Privacy</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Footer end -->
    </div>

    <!-- Back to Top ============================================= -->
    <a id="back-to-top" data-toggle="tooltip" title="Back to Top" href="javascript:void(0)"><i class="fa fa-chevron-up"></i></a>

    <!-- Video Modal ============================================= -->
    <div class="modal fade" id="videoModal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
            <div class="modal-content bg-transparent border-0">
                <button type="button" class="close text-white opacity-10 ml-auto mr-n3 font-weight-400" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <div class="modal-body p-0">
                    <div class="embed-responsive embed-responsive-16by9">
                        <iframe class="embed-responsive-item" id="video" allow="autoplay"></iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Video Modal end -->

    <!-- Scripts -->
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"
                integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
                crossorigin="anonymous"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
                crossorigin="anonymous"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
    </environment>
    @await this.RenderSectionAsync("Scripts", required: false)
    <environment include="Development">
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="/js/custom.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
</body>
</html>

Wallet App/src/Web/PaymentSystem.WalletApp.Web/Views/Shared/_ProfileWithSecondaryMenuLayout.cshtml
@model PaymentSystem.WalletApp.Web.ViewModels.Profile.ProfileLayout.ProfileLayoutUserModel

@{
    Layout = "_ProfileLayout.cshtml";
}

@section SecondaryMenu
{
    <div class="bg-primary">
        <div class="container d-flex justify-content-center">
            <ul class="nav secondary-nav">
                <li class="nav-item">
                    <a is-active-route="active" asp-area="Profile" asp-controller="Users" asp-action="Index" class="nav-link">Profile</a>
                </li>
                <li class="nav-item">
                    <a is-active-route="active" asp-area="Profile" asp-controller="Financials" asp-action="Index" class="nav-link">Cards & Bank Accounts</a>
                </li>
                <li class="nav-item">
                    <a is-active-route="active" asp-area="Profile" asp-controller="Accounts" asp-action="Index" class="nav-link">Coin Accounts</a>
                </li>
            </ul>
        </div>
    </div>
}

@section Styles{
    @await this.RenderSectionAsync("Styles", required: false)
}

@section Scripts{
    @await this.RenderSectionAsync("Scripts", required: false)
}

@this.RenderBody();