Wallet App/src/Web/PaymentSystem.WalletApp.Web/Areas/Administration/Controllers/DashboardController.cs
namespace PaymentSystem.WalletApp.Web.Areas.Administration.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;

    using PaymentSystem.WalletApp.Services.Data;
    using PaymentSystem.WalletApp.Web.ViewModels.Administration.Accounts;
    using PaymentSystem.WalletApp.Web.ViewModels.Administration.Blocks;
    using PaymentSystem.WalletApp.Web.ViewModels.Administration.Dashboard;
    using PaymentSystem.WalletApp.Web.ViewModels.Administration.Users;

    public class DashboardController : AdministrationController
    {
        private readonly IAccountService accountService;
        private readonly IBlockService blockService;
        private readonly IUserService userService;

        public DashboardController(
            IAccountService accountService,
            IBlockService blockService,
            IUserService userService)
        {
            this.accountService = accountService;
            this.blockService = blockService;
            this.userService = userService;
        }

        public async Task<IActionResult> Index()
        {
            var model = new AdminDashboardIndexViewModel()
            {
                Accounts = await this.accountService.GetLatestAccounts<AccountListingAdminModel>(),
                Blocks = await this.blockService.GetLatestBlocks<BlockListingAdminModel>(),
                Users = await this.userService.GetLatestRegisteredUsers<UserListingAdminModel>(),
            };

            return this.View(model);
        }
    }
}

Wallet App/src/Web/PaymentSystem.WalletApp.Web/Areas/Administration/Controllers/UsersController.cs
namespace PaymentSystem.WalletApp.Web.Areas.Administration.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;

    using PaymentSystem.WalletApp.Services.Data;
    using PaymentSystem.WalletApp.Web.ViewModels.Administration.Users;

    using static Infrastructure.WebConstants;

    public class UsersController : AdministrationController
    {
        private readonly IUserService userService;

        public UsersController(IUserService userService)
        {
            this.userService = userService;
        }

        public async Task<IActionResult> Index(int page = 1)
        {
            var currentPageSize = DefaultUsersResultPageSize;

            var (totalPages, users) = await this.Pagination(
                this.userService.GetUsers<UserListingAdminModel>,
                page,
                currentPageSize);

            var model = new UsersIndexAdminViewModel()
            {
                CurrentPage = page,
                TotalPages = totalPages,
                Users = users,
            };

            return this.View(model);
        }

        public async Task<IActionResult> Details(string id)
        {
            var model = await this.userService.GetUser<UserDetailsAdminModel>(id);

            return this.View(model);
        }
    }
}

Wallet App/src/Web/PaymentSystem.WalletApp.Web/Controllers/ActivitiesController.cs
namespace PaymentSystem.WalletApp.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    using PaymentSystem.WalletApp.Data.Models;
    using PaymentSystem.WalletApp.Services.Data;
    using PaymentSystem.WalletApp.Web.Infrastructure;
    using PaymentSystem.WalletApp.Web.ViewModels.Activities;
    using PaymentSystem.WalletApp.Web.ViewModels.Activities.Index;

    [Authorize]
    public class ActivitiesController : BaseController
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IActivityService activityService;

        public ActivitiesController(
            UserManager<ApplicationUser> userManager,
            IActivityService activityService)
        {
            this.userManager = userManager;
            this.activityService = activityService;
        }

        public async Task<IActionResult> Index(int page = 1, string dateRange = "")
        {
            page = Math.Max(page, 1);

            var userId = this.userManager.GetUserId(this.User);

            var (total, activities) = await this.activityService
                .GetUserActivities<DetailsActivityModel>(
                    userId,
                    page,
                    WebConstants.DefaultActivitiesResultPageSize,
                    dateRange);

            var model = new ActivitiesIndexViewModel()
            {
                Activities = activities,
                DateRange = dateRange,
                CurrentPage = page,
                TotalPages = (int)Math.Ceiling(total / (double)WebConstants.DefaultActivitiesResultPageSize),
            };

            return this.View(model);
        }
    }
}

Wallet App/src/Web/PaymentSystem.WalletApp.Web/Controllers/FinancialsController.cs
namespace PaymentSystem.WalletApp.Web.Controllers
{
    using System.Text;
    using System.Threading.Tasks;

    using AutoMapper;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Options;

    using PaymentSystem.WalletApp.Data.Models;
    using PaymentSystem.WalletApp.Services;
    using PaymentSystem.WalletApp.Services.Data;
    using PaymentSystem.WalletApp.Services.Data.Models.BankAccounts;
    using PaymentSystem.WalletApp.Services.Data.Models.CreditCards;
    using PaymentSystem.WalletApp.Web.Infrastructure.Helpers;
    using PaymentSystem.WalletApp.Web.Infrastructure.Options;
    using PaymentSystem.WalletApp.Web.ViewModels.Financials.Profile;

    [Authorize]
    public class FinancialsController : ProfileController
    {
        private readonly ICreditCardService creditCardService;
        private readonly IBankAccountService bankAccountService;
        private readonly IFingerprintService fingerprintService;
        private readonly IOptions<EncryptionOptions> encryptionOptions;

        public FinancialsController(
            UserManager<ApplicationUser> userManager,
            IMapper mapper,
            ICloudinaryService cloudinaryService,
            IUserService userService,
            ICreditCardService creditCardService,
            IBankAccountService bankAccountService,
            IFingerprintService fingerprintService,
            IOptions<EncryptionOptions> encryptionOptions) 
            : base(userManager, mapper, cloudinaryService, userService)
        {
            this.creditCardService = creditCardService;
            this.bankAccountService = bankAccountService;
            this.fingerprintService = fingerprintService;
            this.encryptionOptions = encryptionOptions;
        }

        public async Task<IActionResult> Profile()
        {
            var profileUser = await this.GetUserProfile();

            return this.View(profileUser);
        }

        [HttpPost]
        public async Task<IActionResult> AddCreditCard(AddCreditCardProfileModel model)
        {
            if (await this.fingerprintService.Exists(model.CardNumber))
            {
                this.ModelState.AddModelError(string.Empty, "Card number already exists.");
            }

            if (!this.ModelState.IsValid)
            {
                var profileUser = await this.GetUserProfile();
                return this.View(nameof(this.Profile), profileUser);
            }

            var serviceModel = this.mapper.Map<AddCreditCardServiceModel>(model);
            var userId = this.userManager.GetUserId(this.User);
            var key = Encoding.UTF8.GetBytes(this.encryptionOptions.Value.Key);

            await this.creditCardService.AddCreditCard(serviceModel, userId, key);

            var controller = ControllerHelpers.GetControllerName<FinancialsController>();
            return this.Redirect($"/{controller}/{nameof(this.Profile)}");
        }

        [HttpPost]
        public async Task<IActionResult> EditCreditCard(EditCreditCardModel model)
        {
            var userId = this.userManager.GetUserId(this.User);

            if (!await this.creditCardService.UserOwnsCard(model.Id, userId))
            {
                return this.BadRequest();
            }

            if (!this.ModelState.IsValid)
            {
                var profileUser = await this.GetUserProfile();
                return this.View(nameof(this.Profile), profileUser);
            }

            var key = Encoding.UTF8.GetBytes(this.encryptionOptions.Value.Key);

            var serviceModel = this.mapper.Map<EditCreditCardServiceModel>(model);
            await this.creditCardService.UpdateCardInformation(key, serviceModel);

            var controller = ControllerHelpers.GetControllerName<UsersController>();
            return this.Redirect($"/{controller}/{nameof(this.Profile)}");
        }

        public async Task<IActionResult> GetCreditCardDetails(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
            {
                return this.BadRequest();
            }

            if (!await this.creditCardService.Exists(id))
            {
                return this.BadRequest();
            }

            var userId = this.userManager.GetUserId(this.User);

            if (!await this.creditCardService.UserOwnsCard(id, userId))
            {
                return this.BadRequest();
            }

            var key = Encoding.UTF8.GetBytes(this.encryptionOptions.Value.Key);

            var model = await this.creditCardService.GetCardInformation(id, key);
            return this.Ok(model);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteCreditCard(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
            {
                return this.BadRequest();
            }

            if (!await this.creditCardService.Exists(id))
            {
                return this.BadRequest();
            }

            var userId = this.userManager.GetUserId(this.User);

            if (!await this.creditCardService.UserOwnsCard(id, userId))
            {
                return this.BadRequest();
            }

            await this.creditCardService.DeleteCreditCard(id);

            var controller = ControllerHelpers.GetControllerName<FinancialsController>();
            return this.Redirect($"/{controller}/{nameof(this.Profile)}");
        }

        [HttpPost]
        public async Task<IActionResult> AddBankAccount(AddBankAccountProfileModel model)
        {
            if (!this.ModelState.IsValid)
            {
                var profileUser = await this.GetUserProfile();
                return this.View(nameof(this.Profile), profileUser);
            }

            var userId = this.userManager.GetUserId(this.User);

            var serviceModel = this.mapper.Map<AddBankAccountServiceModel>(model);
            await this.bankAccountService.AddAccount(serviceModel, userId);

            var controller = ControllerHelpers.GetControllerName<FinancialsController>();
            return this.Redirect($"/{controller}/{nameof(this.Profile)}");
        }

        public async Task<IActionResult> GetBankAccountDetails(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
            {
                return this.BadRequest();
            }

            if (!await this.bankAccountService.Exists(id))
            {
                return this.BadRequest();
            }

            var userId = this.userManager.GetUserId(this.User);

            if (!await this.bankAccountService.UserOwnsAccount(id, userId))
            {
                return this.BadRequest();
            }

            var model = await this.bankAccountService.GetAccountInformation<ProfileDeleteBankAccountModel>(id);
            return this.Ok(model);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteBankAccount(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
            {
                return this.BadRequest();
            }

            if (!await this.bankAccountService.Exists(id))
            {
                return this.BadRequest();
            }

            await this.bankAccountService.DeleteAccount(id);

            var controller = ControllerHelpers.GetControllerName<FinancialsController>();
            return this.Redirect($"/{controller}/{nameof(this.Profile)}");
        }

        private async Task<ProfileFinancialViewModel> GetUserProfile()
        {
            var profileUser = await this.GetProfileUser<ProfileFinancialViewModel>();

            profileUser.CreditCards = await this.creditCardService.GetCreditCards<ProfileCreditCardModel>(profileUser.Id);
            profileUser.BankAccounts = await this.bankAccountService.GetAccounts<ProfileBankAccountModel>(profileUser.Id);

            return profileUser;
        }
    }
}

Wallet App/src/Web/PaymentSystem.WalletApp.Web/Areas/Profile/Views/Users/Dashboard.cshtml
@model PaymentSystem.WalletApp.Web.ViewModels.Profile.Users.Dashboard.DashboardUser

@{
    var completenessFactors = new[]
    {
        this.Model.HasEmailAdded,
        this.Model.HasPhoneAdded,
        this.Model.HasBankAccountAdded,
        this.Model.HasCardAdded,
    };

    var completeness = (completenessFactors.Count(f => f)) / (double)completenessFactors.Count() * 100;
}

<!-- Middle Panel ============================================= -->
<div class="col-lg-9">

    <!-- Profile Completeness =============================== -->
    <div class="bg-light shadow-sm rounded p-4 mb-4">
        <h3 class="text-5 font-weight-400 d-flex align-items-center mb-3">Profile Completeness <span class="bg-light-4 text-success rounded px-2 py-1 font-weight-400 text-2 ml-2">@($"{completeness}%")</span></h3>
        <div class="row profile-completeness">

            <div class="col-sm-6 col-md-3 mb-4 mb-md-0">
                <div class="border rounded p-3 text-center">
                    <span class="d-block text-10 text-light mt-2 mb-3">
                        <i class="fas fa-mobile-alt"></i>
                    </span>
                    @if (this.Model.HasPhoneAdded)
                    {
                        <span class="text-5 d-block text-success mt-4 mb-3">
                            <i class="fas fa-check-circle"></i>
                        </span>
                        <p class="mb-0">Phone Added</p>
                    }
                    else
                    {
                        <span class="text-5 d-block text-light mt-4 mb-3">
                            <i class="far fa-circle "></i>
                        </span>
                        <p class="mb-0">
                            <a class="btn-link stretched-link" asp-area="" asp-controller="Users" asp-action="Index">Add Phone</a>
                        </p>
                    }
                </div>
            </div>

            <div class="col-sm-6 col-md-3 mb-4 mb-md-0">
                <div class="border rounded p-3 text-center">
                    <span class="d-block text-10 text-light mt-2 mb-3">
                        <i class="fas fa-envelope"></i>
                    </span>
                    @if (this.Model.HasEmailAdded)
                    {
                        <span class="text-5 d-block text-success mt-4 mb-3">
                            <i class="fas fa-check-circle"></i>
                        </span>
                        <p class="mb-0">Email Added</p>
                    }
                    else
                    {
                        <span class="text-5 d-block text-light mt-4 mb-3">
                            <i class="far fa-circle "></i>
                        </span>
                        <p class="mb-0">
                            <a class="btn-link stretched-link" asp-area="" asp-controller="Users" asp-action="Index">Add Email</a>
                        </p>
                    }
                </div>
            </div>

            <div class="col-sm-6 col-md-3 mb-4 mb-sm-0">
                <div class="border rounded p-3 text-center">
                    <span class="d-block text-10 text-light mt-2 mb-3">
                        <i class="fas fa-credit-card"></i>
                    </span>
                    @if (this.Model.HasCardAdded)
                    {
                        <span class="text-5 d-block text-success mt-4 mb-3">
                            <i class="fas fa-check-circle"></i>
                        </span>
                        <p class="mb-0">Card Added</p>
                    }
                    else
                    {
                        <span class="text-5 d-block text-light mt-4 mb-3">
                            <i class="far fa-circle "></i>
                        </span>
                        <p class="mb-0">
                            <a class="btn-link stretched-link" asp-area="" asp-controller="Financials" asp-action="Index">Add Card</a>
                        </p>
                    }
                </div>
            </div>

            <div class="col-sm-6 col-md-3">
                <div class="border rounded p-3 text-center">
                    <span class="d-block text-10 text-light mt-2 mb-3">
                        <i class="fas fa-university"></i>
                    </span>
                    @if (this.Model.HasBankAccountAdded)
                    {
                        <span class="text-5 d-block text-success mt-4 mb-3">
                            <i class="fas fa-check-circle"></i>
                        </span>
                        <p class="mb-0">Bank Added</p>
                    }
                    else
                    {
                        <span class="text-5 d-block text-light mt-4 mb-3">
                            <i class="far fa-circle "></i>
                        </span>
                        <p class="mb-0"><a class="btn-link stretched-link" asp-area="" asp-controller="Financials" asp-action="Index">Add Bank</a></p>
                    }
                </div>
            </div>
        </div>
    </div>
    <!-- Profile Completeness End -->


    <!-- Recent Activity =============================== -->
    <div class="bg-light shadow-sm rounded py-4 mb-4">
        <h3 class="text-5 font-weight-400 d-flex align-items-center px-4 mb-3">Recent Activity</h3>

        @*<vc:activities model="@this.Model.Activities"></vc:activities>*@
        <partial name="/Views/Shared/Components/Activities/Default.cshtml" model="@this.Model.Activities" />

        <!-- View all Link =============================== -->
        <div class="text-center mt-4"><a asp-area="" asp-controller="Activities" asp-action="Index" class="btn-link text-3">View all<i class="fas fa-chevron-right text-2 ml-2"></i></a></div>
        <!-- View all Link End -->

    </div>
    <!-- Recent Activity End -->
</div>
<!-- Middle Panel End -->